##parameters=
# $Id$
"""Return CPSTaskTracker related layouts
"""

cps_task_layout = {
    'widgets': {
        'task_type': {
            'type': 'Select Widget',
            'data': {
                'title': '',
                'fields': ['task_type'],
                'is_required': 1,
                'label': 'label_cps_task_type',
                'label_edit': 'label_cps_task_type',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'vocabulary': 'task_type',
            },
        },
        'start_task_date': {
            'type': 'DateTime Widget',
            'data': {
                'title': '',
                'fields': ['start_task_date'],
                'is_required': 1,
                'label': 'label_cps_start_task_date',
                'label_edit': 'label_cps_start_task_date',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'view_format': 'medium',
                'time_setting': 1,
            },
        },
        'task_priority': {
            'type': 'Select Widget',
            'data': {
                'title': '',
                'fields': ['task_priority'],
                'is_required': 1,
                'label': 'label_cps_task_priority',
                'label_edit': 'label_cps_task_priority',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'vocabulary': 'task_priority',
            },
        },
        'stop_task_date': {
            'type': 'DateTime Widget',
            'data': {
                'title': '',
                'fields': ['stop_task_date'],
                'is_required': 1,
                'label': 'label_cps_stop_task_date',
                'label_edit': 'label_cps_stop_task_date',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'view_format': 'medium',
                'time_setting': 1,
            },
        },
        'task_goal': {
            'type': 'Text Widget',
            'data': {
                'title': '',
                'fields': ['task_goal'],
                'is_required': 0,
                'label': 'label_cps_task_goal',
                'label_edit': 'label_cps_task_goal',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'width': 40,
                'height': 5,
                'size_max': 0,
                'render_position': 'normal',
                'render_format': 'html',
                'configurable': 'format',
            },
        },
        'Title': {
            'type': 'String Widget',
            'data': {
                'title': '',
                'fields': ['Title'],
                'is_required': 1,
                'label': 'Title',
                'label_edit': 'Title',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'display_width': 60,
                'size_max': 0,
            },
        },
        'Description': {
            'type': 'TextArea Widget',
            'data': {
                'title': '',
                'fields': ['Description'],
                'is_required': 1,
                'label': 'label_cps_task_description',
                'label_edit': 'label_cps_task_description',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'width': 60,
                'height': 5,
                'render_format': 'text',
            },
        },
        'members': {
            'type': 'Directory MultiEntries Widget',
            'data': {
                'title': '',
                'fields': ['members'],
                'is_required': 1,
                'label': 'label_cps_task_members',
                'label_edit': 'label_cps_task_members',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'vocabulary': 'members',
                'size': 0,
                'format_empty': '[]',
                'directory': 'members',
                'directory_view': '',
                'entry_type': 'id',
                'skin_name': 'cpsdirectory_entry_view',
                'separator': ', ',
                'popup_mode': 'search',
            },
        },
        'groups': {
            'type': 'Directory MultiEntries Widget',
            'data': {
                'title': '',
                'fields': ['groups'],
                'is_required': 0,
                'label': 'label_cps_task_groups',
                'label_edit': 'label_cps_task_groups',
                'description': '',
                'help': '',
                'is_i18n': 1,
                'readonly_layout_modes': [],
                'hidden_layout_modes': [],
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'vocabulary': 'groups',
                'size': 0,
                'format_empty': '[]',
                'directory': 'groups',
                'directory_view': '',
                'entry_type': 'id',
                'skin_name': 'cpsdirectory_entry_view',
                'separator': ', ',
                'popup_mode': 'search',
            },
        },
    },
    'layout': {
        'style_prefix': 'layout_default_',
        'flexible_widgets': [],
        'ncols': 1,
        'rows': [
            [{'ncols': 1, 'widget_id': 'Title'},
            ],
            [{'ncols': 1, 'widget_id': 'Description'},
            ],
            [{'ncols': 1, 'widget_id': 'start_task_date'},
            ],
            [{'ncols': 1, 'widget_id': 'stop_task_date'},
            ],
            [{'ncols': 1, 'widget_id': 'task_type'},
            ],
            [{'ncols': 1, 'widget_id': 'task_priority'},
            ],
            [{'ncols': 1, 'widget_id': 'task_goal'},
            ],
            [{'ncols': 1, 'widget_id': 'members'},
            ],
            [{'ncols': 1, 'widget_id': 'groups'},
            ],
        ],
    },
}

task_tracker_layouts = {}
task_tracker_layouts['cps_task'] = cps_task_layout
return task_tracker_layouts
